### ISSUE TITLE
SaslException: SASL authentication failed.

### ISSUE THREAD

**Issue by stefanoriva79** [araditc/Artalk.Xmpp#7]
I have no way to connect.

Basically I'm using this syntax buit without any chance to connect:

     Dim client As New ArtalkXmppClient("portal.global.it", "userxx@server", "passwd", "443", False)

The domain of the portal is server and host is different.

How can I set domain? I tried with @ without success.

Thnaks
Stefano

**Comment by rlkollman** [comment]
I am experiencing this as well. An application using the XmppCore class that was functioning just fine a few weeks ago is now throwing this same exception.  I made no changes to my application, including no updates to any other class/library.  It appears something within this repo has become broken.

I am using this within a Windows Service.  From Windows Event Viewer:
Service cannot be started. System.Security.Authentication.AuthenticationException: Authentication failed. ---> Artalk.Xmpp.Core.Sasl.SaslException: SASL authentication failed.
   at Artalk.Xmpp.Core.XmppCore.Authenticate(IEnumerable`1 mechanisms, String username, String password, String hostname)
   at Artalk.Xmpp.Core.XmppCore.SetupConnection(String resource)
   --- End of inner exception stack trace ---
   at Artalk.Xmpp.Core.XmppCore.SetupConnection(String resource)
   at Artalk.Xmpp.Core.XmppCore.Connect(String resource)
   at NwwsService.NwwsService.ConnectToXmpp()
   at NwwsService.NwwsService.OnStart(String[] args)
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

**Comment by ammarheidari** [comment]
Hi
Can you share me your windows service code?
